version: "3"
services:
  web:
    build: ./api
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./api:/opt/api:delegated
    command: ["npm", "run", "start:dev"]

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idm
